version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  
  build:
    commands:
      - npm run build
  
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://app-deployment-view
      - aws cloudfront create-invalidation --distribution-id E2Z8UF2ASR28NH --path /*\*

artifacts:
  files:
    - '**/**'
  
  discard-paths: no
  base-directory: build
